server:
  port: 8088

api:
  prefix: /api/v1

spring:
  datasource:
    url: jdbc:mysql://music-web-hk241-tai21042004.i.aivencloud.com:23837/music_web_db?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_inUhMnWdGGI-v3mJmss
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Không tự động tạo/tạo lại bảng, phù hợp khi bạn đã tạo bảng từ Workbench
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Email sender (cần phải tự tạo 1 file chứa username và password)
  config:
    import: "optional:classpath:sensitive-config.yml"
  mail:
    host: smtp.gmail.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

cloudinary:
  cloud_name: dq76uikpj
  api_key: 252687583593391
  api_secret: bBRpdVI_fvwi2-qchZek5_uGfeM

jwt:
  expiration: 2592000 # 30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 # 60 days = 60 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=




